services:
- docker

before_install:
- docker pull ldumas/sirius_dockerfile:sirius
- docker volume ls
- ls -l $HOME
- ls -l $HOME/*

script:
- docker run -v $HOME/sirius_doc_pages:/sirius_doc_pages ldumas/sirius_dockerfile:sirius /bin/sh -c "echo $PWD; cd /sirius_doc_pages/; ls -l; ls -l sphinx/"


after_success:
- .travis/on_success.sh
