lannguage: python

services:
- docker

before_install:
- docker pull ldumas/sirius_dockerfile:sirius
- docker volume ls
- echo $HOME
- echo $TRAVIS_BUILD_DIR
- ls -l $TRAVIS_BUILD_DIR
- ls -l $TRAVIS_BUILD_DIR/*

script:
- docker run -v $TRAVIS_BUILD_DIR/sphinx:/sphinx ldumas/sirius_dockerfile:sirius /bin/sh -c "echo $PWD; ls -l"


after_success:
- .travis/on_success.sh
